LOAD DATA
INFILE *
INTO TABLE IMAGES 
REPLACE
FIELDS TERMINATED BY ','
(
 id    INTEGER(5),
 name  CHAR(50),
 image LOBFILE (name) TERMINATED BY EOF
)
BEGINDATA
001,OracleHQ1.jpg
002,oracleHQ2.jpg
003,OracleHQ3.jpg
